### 超级用户登录
POST {{baseUrl}}/api/login
Accept: application/json
_auth_type_key_: admin
X-Auth-Token: {{randomKey}}

> {% client.global.set("auth_token", response.headers.valueOf("X-Auth-Token")); %}

### 普通用户登录-standard
POST {{baseUrl}}/api/login
Accept: application/json
_auth_type_key_: standard
tenantId: 10000
userType: phone
user: M18888888888
pass: abc!123

> {% client.global.set("auth_token", response.headers.valueOf("X-Auth-Token")); %}

### 普通用户登录-captcha
POST {{baseUrl}}/api/login
Accept: application/json
_auth_type_key_: dynamic-captcha
tenantId: 10000
targetType: phone
target: C18888888881
captcha: 425162

> {% client.global.set("auth_token", response.headers.valueOf("X-Auth-Token")); %}

### 退出
GET {{baseUrl}}/logout
X-Auth-Token: {{auth_token}}

### 获取当前登录用户
GET {{baseUrl}}/authorizations/me
X-Auth-Token: {{auth_token}}

### 增加租户
POST {{baseUrl}}/tenants
Accept: application/json
Content-Type: application/json
X-Auth-Token: {{auth_token}}

{
  "id": 10000,
  "code": "DongFaBao",
  "name": "懂法宝科技股份有限公司",
  "prefix": "dfb"
}

### 增加系统参数
POST {{baseUrl}}/parameters
Accept: application/json
Content-Type: application/json
X-Auth-Token: {{auth_token}}

{
  "groupKey": "test",
  "itemKey": "test",
  "itemValue": "test",
  "tenantId": null
}

### 刷新系统参数
POST {{baseUrl}}/parameters/refresh
Content-Type: application/x-www-form-urlencoded
X-Auth-Token: {{auth_token}}

tenantId=10000&groupKey=SubMail

### 获取系统参数列表
GET {{baseUrl}}/parameters
Accept: application/json
X-Auth-Token: {{auth_token}}

### 增加组织机构
POST {{baseUrl}}/organizations
Accept: application/json
Content-Type: application/json
X-Auth-Token: {{auth_token}}

{
  "code": "DongFaBao",
  "name": "懂法宝科技股份有限公司"
}

### 查询顶层组织机构
GET {{baseUrl}}/organizations/parent
Accept: application/json
Content-Type: application/json
X-Auth-Token: {{auth_token}}

### 增加角色
POST {{baseUrl}}/roles
Accept: application/json
Content-Type: application/json
X-Auth-Token: {{auth_token}}

{
  "name": "aaa",
  "tenantId": "10000"
}

### 查询单一角色
GET {{baseUrl}}/roles/334273880163950592
Accept: application/json
Content-Type: application/json
X-Auth-Token: {{auth_token}}

### 获取所有的API资源
GET {{baseUrl}}/authorizations/acl
Accept: application/json
Content-Type: application/json
X-Auth-Token: {{auth_token}}

### 新建用户
POST {{baseUrl}}/users
Accept: application/json
Content-Type: application/json
X-Auth-Token: {{auth_token}}

{
  "username": "M18888888888",
  "phone": "M18888888888",
  "nickname": "测试账号",
  "password": "abc!123",
  "tenantId": 10000
}

### 查询当前用户或者指定用户
GET {{baseUrl}}/users/me
Accept: application/json
Content-Type: application/json
X-Auth-Token: {{auth_token}}

### 修改当前用户密码
POST {{baseUrl}}/users/change/password
Content-Type: application/x-www-form-urlencoded
X-Auth-Token: {{auth_token}}

oPass=abc!123&nPass=abc!123

### 登录短信验证码
POST {{baseUrl}}/api/sms/login/captcha
Content-Type: application/x-www-form-urlencoded

sender=SubMail&tenantId=10000&to=18888888881&template=abc&target=C18888888881&addUser=true

### 查询当前用户顾客信息
GET {{baseUrl}}/dfb/customers
Accept: application/json
Content-Type: application/json
X-Auth-Token: {{auth_token}}

### 增加虚拟评价
POST {{baseUrl}}/dfb/orders/comments
Accept: application/json
Content-Type: application/json
X-Auth-Token: {{auth_token}}

{
  "customer": "18888888888",
  "lawyer": "张长弓",
  "content": "虚拟评价",
  "value": 4
}

### 查询评价列表
GET {{baseUrl}}/dfb/orders/comments?page=0&size=20
X-Auth-Token: {{auth_token}}

### 查询公开评价列表
GET {{baseUrl}}/api/dfb/comment/list?page=0&size=5
X-Auth-Token: {{auth_token}}

### 查询评价标签统计
GET {{baseUrl}}/api/dfb/comment/count/label
X-Auth-Token: {{auth_token}}

### 咨询律师
POST {{baseUrl}}/dfb/customers/call
Content-Type: application/x-www-form-urlencoded
X-Auth-Token: {{auth_token}}

### 查询当前用户律师信息
GET {{baseUrl}}/dfb/lawyers
Accept: application/json
Content-Type: application/json
X-Auth-Token: {{auth_token}}

### 审核律师信息
POST {{baseUrl}}/dfb/lawyers/approve/378416746235203584
X-Auth-Token: {{auth_token}}

### 律师上班
POST {{baseUrl}}/dfb/lawyers/duty/on
X-Auth-Token: {{auth_token}}

### 律师下班
POST {{baseUrl}}/dfb/lawyers/duty/off
X-Auth-Token: {{auth_token}}