@startuml
'https://plantuml.com/state-diagram
hide empty description
律师未接 --> [*]
完成 --> [*]
免单 --> [*]
已支付 --> [*]
未接通 --> [*]

[*] --> 已创建: 创建订单
已创建 --> 律师接听: 回调成功
已创建 --> 律师未接: 回调失败
已创建 --> 回调超时: 65秒未收到回调
律师接听 --> 通话中: 推送接通
律师接听 --> 未接通: 推送通话结束
律师接听 --> 接通超时: 65秒未收到推送接通
通话中 --> 未支付: 推送通话结束,通话90秒以上含90秒
通话中 --> 完成: 推送通话结束,通话90秒以内
通话中 --> 通话超时: 90分钟未收到推送通话结束
未支付 --> 已支付: 支付成功
未支付 -[#red,dashed]-> 免单: 后台操作
回调超时 -[#red,dashed]-> 人工干预
接通超时 -[#red,dashed]-> 人工干预
通话超时 -[#red,dashed]-> 人工干预

state 未接通 {
    未接通:律师接通后用户挂断/律师挂断/用户未接
}

state 人工干预 #FFFF77 {
    人工干预 -[#red,dashed]-> 律师未接: 后台操作
    人工干预 -[#red,dashed]-> 未接通: 后台操作
    人工干预 -[#red,dashed]-> 未支付: 后台操作
    人工干预 -[#red,dashed]-> 完成: 后台操作
    人工干预: 人工后台操作，不计入状态节点
}

@enduml